
export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <b>1111</b>
        {children}
    </>
  );
}
